### ISSUE TITLE
AdBlocker support

### ISSUE THREAD

**Issue by josiah0** [nfl/react-gpt#8] opened 2016-11-10 17:33 UTC
We're using this library in our site, however it breaks pretty badly when the user has an ad blocker enabled.

How amiable to a patch which is more defensive when ad blockers are in play?

**Comment by taak77** [comment] 2016-11-11 00:33
Hi @josiah0, can you describe how badly it breaks? ad blocker blocks GPT request to render an ad, so if GPT request is blocked, `react-gpt` just render nothing except for the bounding box and won't occupy any space unless you style the bounding box yourself.

There are multiple ways to detect ad blocker in your code(e.g. http://www.detectadblock.com/), maybe your site can implement the ad blocker detection and reflect the decision whether you should render GPT component or not?

**Comment by josiah0** [comment] 2016-11-11 04:44
It breaks pretty badly, is most cases rendering the site unusable. The ad blocker detection is a good idea, I'll put that in place for now.

**Comment by taak77** [comment] 2016-11-18 18:49
@josiah0 i'm closing this ticket as long as `react-gpt` just fails to render an ad because of ad blocker and not causing any visual side effect to make your page looks like broken. If your page layout relies on `react-gpt` always taking up the space as ad size, you can have a wrapper which takes up that space even if ad is blocked so that your page layout expectation remains same.

Feel free to re-open it otherwise.

**Closed by taak77** 2016-11-18 18:49 UTC

**Comment by JakeGinnivan** [comment] 2016-12-07 12:10
The issue is that react-gpt assumes that the elements will be created and has little error checking in this area.

Ad blockers just delete the markup that is created then when react-gpt tries to access them later things blow up.

**Comment by jbyers** [comment] 2017-07-20 02:14
May be addressed by https://github.com/nfl/react-gpt/pull/24
