### ISSUE TITLE
enableSingleRequest still doing multiple requests

### ISSUE THREAD

**Issue by jpklzm** [nfl/react-gpt#59] opened 2017-10-19 17:00 UTC
I'm facing an issue with the enableSingleRequest function.

When I load my page, it works and I only receive a single request with all my slot sizes.
![captura de tela 2017-10-19 as 14 35 25](https://user-images.githubusercontent.com/8094284/31783235-57f2d024-b4dc-11e7-939b-d2c14e2b5221.png)
![captura de tela 2017-10-19 as 14 35 48](https://user-images.githubusercontent.com/8094284/31783245-5f2ac6ee-b4dc-11e7-8c13-73e0084a81fe.png)

but when I navigate on my app, I receive multiple requests, one for each slot size.
![captura de tela 2017-10-19 as 14 36 42](https://user-images.githubusercontent.com/8094284/31783303-8ed1a0d4-b4dc-11e7-811e-9ba4ddb90a04.png)
![captura de tela 2017-10-19 as 14 37 02](https://user-images.githubusercontent.com/8094284/31783309-94d4efa4-b4dc-11e7-8c73-7e0dfd7252fc.png)
![captura de tela 2017-10-19 as 14 37 14](https://user-images.githubusercontent.com/8094284/31783311-967be600-b4dc-11e7-923a-e3b0576988f3.png)

I'm calling the function outside my app, covering all my pages.

![captura de tela 2017-10-19 as 14 49 22](https://user-images.githubusercontent.com/8094284/31783654-da347d84-b4dd-11e7-9442-2839d4fe9797.png)

Any idea about how to solve this problem?

**Comment by jpklzm** [comment] 2017-10-24 16:42
@taak77 @jamsea Any thoughts?

**Comment by potench** [comment] 2017-11-01 21:54
I've looked into reproducing this issue within the react-gpt "routing" example project: https://github.com/nfl/react-gpt/tree/master/examples/apps/routing

Initial requests collapse into a single request, subsequent requests don't. I found this documentation for GPT:

> Enables single request mode for fetching multiple ads at the same time. This requires all pubads slots to be defined and added to the pubads service prior to enabling the service. Single request mode must be set before the service is enabled.
> https://developers.google.com/doubleclick-gpt/reference

You would need to define all slots before calling `enableSingleRequest`, any slot created afterwards results in a separate request. If you can find any documentation on best practices for achieving this on single page apps, then maybe include it here and we can add it to the documentation?

**Comment by potench** [comment] 2017-11-01 22:02
Watch this video for best practices around using `enableSingleRequest`, it discusses "Batch SRA" which is what you are looking for.
1. You need to define all slots (which could be problematic for a SPA)
2. Turn on `enableSingleRequest` and turn on `disableInitialLoad`
3. When you're ready to request ads, use `refresh(slot1, slot2...)` to batch multiple requests. 

I'm closing this issue for now, feel free to re-open if you feel there's a problem with react-gpt.

**Closed by potench** 2017-11-01 22:02 UTC

**Comment by pgsil** [comment] 2017-12-14 16:43
An update on this issue: I've tried several different approaches to this problem, both trying to `enableSingleRequest` and `disableInitialLoad` and to just do one request per ad, but so far I haven't found any solution.

At first, doing a single request was ideal for our product, because we have a background ad that needs to be synced with a banner ad for a seamless look. However, the product also needs lazy loading now, so `enableSingleRequest` wouldn't work... even if I could get it to behave.

After trying several different approaches, this is the only one that work: on a parent component, `enableSingleRequest` would be called whenever a navigation/page change happened. Then, a `refresh()`. 
At this point, the ads were synced - they weren't getting mixed up any more, but we had one request for each ad and *then* a request that included every slot. But lazy load becomes a problem with that approach.

Is `enableSingleRequest` really the solution here?

**Comment by nandosangenetto** [comment] 2017-12-18 12:49
Hey @potench, do you have any suggestion about this problem?

**Comment by alexander-morozov** [comment] 2018-05-11 15:05
I faced with this issue and found a reason and workaround.
A reason is that on the first render all GPTs render by AdManager and it works properly. It waits until all GPTs  will be mounted, after that it defines slots for every GPT and only after that it calls `display`. It means that if we have 5 GPT items. than slots for all of them will be defined before first `display` will be called. 
For the other way, when we go to another page and AdManager was already initialized, all GPTs render by themselves. It means that first GPT calls `defineSlot` and immediately after that calls `display`. So, they don't wait until all GPT call `defineSlot`.

My workaround:
`GPT.on(Events.RENDER, () => {
    setTimeout(() => {
      GPT._adManager._initialRender = true
    })
  })`

@potench but I'm sure that it can be done inside the library. Does it make sense?

**Comment by alexander-morozov** [comment] 2018-05-11 15:43
I just realized that according to the official [official documentation](https://developers.google.com/doubleclick-gpt/reference#googletag.PubAdsService_enableSingleRequest) my workaround above shouldn't work as slots are defined after `enableSingleRequest`, but it works =)

**Comment by jackson-sandland** [comment] 2019-07-31 00:05
I'm running into this exact same issue. 
Is there an established pattern to: 
```
Create one SRA request with all ad slots to best serve guaranteed
roadblocks or competitive exclusions, instead of sending 
SRA requests with one ad slot at a time.
```
in a react application?
